server:
  port: 9976
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.50.176:3306/shop?useUnicode=true&characterEncoding=utf8
    username: ryan
    password: ryan
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9009/eureka/
  instance:
    prefer-ip-address: true #使用ip地址进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中心中注入服务id
    lease-renewal-interval-in-seconds: 5 #向注册中心发送的心跳间隔
    lease-expiration-duration-in-seconds: 10 #续约到期时间